#!/bin/sh
set -eu

if [ -z "${SSH_CONNECTION+x}" ] || have-dropped-all-caps; then
    # not an ssh connection, don't take away their fun
    exec bash "$@"
fi

exec drop-all-caps drop-privs-harder bash "$@"

